### ISSUE TITLE
"proto error" was returned from lookup_ip

### ISSUE THREAD

**Issue by zonyitoo** [bluejekyll/trust-dns#905]
**Describe the bug**

I was using `AsyncResolver` with `read_system_conf()`. I have got "proto error" when resolving any addresses. Some useful logs are here:

```
[2019-10-29][00:05:09.424859000][TRACE] [trust_dns_resolver::async_resolver::background] AsyncResolver performing lookup_ip
[2019-10-29][00:05:09.425002000][DEBUG] [trust_dns_proto::xfer::dns_handle] querying: www.example.com A
[2019-10-29][00:05:09.425114000][DEBUG] [trust_dns_resolver::name_server::name_server] reconnecting: NameServerConfig { socket_addr: V4(211.148.192.141:53), protocol: Udp, tls_dns_name: None, tls_config: None }
[2019-10-29][00:05:09.425175000][DEBUG] [trust_dns_resolver::name_server::name_server] reconnecting: NameServerConfig { socket_addr: V4(211.148.192.151:53), protocol: Udp, tls_dns_name: None, tls_config: None }
[2019-10-29][00:05:09.425222000][TRACE] [trust_dns_resolver::name_server::connection_provider] polling response inner
[2019-10-29][00:05:09.425247000][DEBUG] [trust_dns_resolver::name_server::connection_provider] connecting: Udp { socket_addr: V4(211.148.192.141:53), timeout: 5s }
[2019-10-29][00:05:09.425309000][DEBUG] [trust_dns_resolver::name_server::name_server] name_server connection failure: tokio spawn error
[2019-10-29][00:05:09.425341000][TRACE] [trust_dns_resolver::name_server::connection_provider] polling response inner
[2019-10-29][00:05:09.425362000][DEBUG] [trust_dns_resolver::name_server::connection_provider] connecting: Udp { socket_addr: V4(211.148.192.151:53), timeout: 5s }
[2019-10-29][00:05:09.425407000][DEBUG] [trust_dns_resolver::name_server::name_server] name_server connection failure: tokio spawn error
[2019-10-29][00:05:09.434640000][DEBUG] [trust_dns_resolver::name_server::name_server] reconnecting: NameServerConfig { socket_addr: V4(211.148.192.141:53), protocol: Tcp, tls_dns_name: None, tls_config: None }
[2019-10-29][00:05:09.434720000][DEBUG] [trust_dns_resolver::name_server::name_server] reconnecting: NameServerConfig { socket_addr: V4(211.148.192.151:53), protocol: Tcp, tls_dns_name: None, tls_config: None }
[2019-10-29][00:05:09.434798000][TRACE] [trust_dns_resolver::name_server::connection_provider] polling response inner
[2019-10-29][00:05:09.434843000][DEBUG] [trust_dns_resolver::name_server::connection_provider] connecting: Tcp { socket_addr: V4(211.148.192.141:53), timeout: 5s }
[2019-10-29][00:05:09.434951000][DEBUG] [trust_dns_resolver::name_server::name_server] name_server connection failure: tokio spawn error
[2019-10-29][00:05:09.434986000][TRACE] [trust_dns_resolver::name_server::connection_provider] polling response inner
[2019-10-29][00:05:09.435031000][DEBUG] [trust_dns_resolver::name_server::connection_provider] connecting: Tcp { socket_addr: V4(211.148.192.151:53), timeout: 5s }
[2019-10-29][00:05:09.435149000][DEBUG] [trust_dns_resolver::name_server::name_server] name_server connection failure: tokio spawn error
[2019-10-29][00:05:09.435292000][DEBUG] [trust_dns_resolver::name_server::name_server] reconnecting: NameServerConfig { socket_addr: V4(211.148.192.151:53), protocol: Udp, tls_dns_name: None, tls_config: None }
[2019-10-29][00:05:09.435547000][DEBUG] [trust_dns_resolver::name_server::name_server] reconnecting: NameServerConfig { socket_addr: V4(211.148.192.141:53), protocol: Udp, tls_dns_name: None, tls_config: None }
[2019-10-29][00:05:09.435617000][TRACE] [trust_dns_resolver::name_server::connection_provider] polling response inner
[2019-10-29][00:05:09.435659000][DEBUG] [trust_dns_resolver::name_server::connection_provider] connecting: Udp { socket_addr: V4(211.148.192.151:53), timeout: 5s }
[2019-10-29][00:05:09.435716000][DEBUG] [trust_dns_resolver::name_server::name_server] name_server connection failure: tokio spawn error
[2019-10-29][00:05:09.435769000][TRACE] [trust_dns_resolver::name_server::connection_provider] polling response inner
[2019-10-29][00:05:09.435791000][DEBUG] [trust_dns_resolver::name_server::connection_provider] connecting: Udp { socket_addr: V4(211.148.192.141:53), timeout: 5s }
[2019-10-29][00:05:09.435845000][DEBUG] [trust_dns_resolver::name_server::name_server] name_server connection failure: tokio spawn error
[2019-10-29][00:05:09.435942000][DEBUG] [trust_dns_resolver::name_server::name_server] reconnecting: NameServerConfig { socket_addr: V4(211.148.192.151:53), protocol: Tcp, tls_dns_name: None, tls_config: None }
[2019-10-29][00:05:09.436003000][DEBUG] [trust_dns_resolver::name_server::name_server] reconnecting: NameServerConfig { socket_addr: V4(211.148.192.141:53), protocol: Tcp, tls_dns_name: None, tls_config: None }
[2019-10-29][00:05:09.436065000][TRACE] [trust_dns_resolver::name_server::connection_provider] polling response inner
[2019-10-29][00:05:09.436107000][DEBUG] [trust_dns_resolver::name_server::connection_provider] connecting: Tcp { socket_addr: V4(211.148.192.151:53), timeout: 5s }
[2019-10-29][00:05:09.436214000][DEBUG] [trust_dns_resolver::name_server::name_server] name_server connection failure: tokio spawn error
[2019-10-29][00:05:09.436287000][TRACE] [trust_dns_resolver::name_server::connection_provider] polling response inner
[2019-10-29][00:05:09.436329000][DEBUG] [trust_dns_resolver::name_server::connection_provider] connecting: Tcp { socket_addr: V4(211.148.192.141:53), timeout: 5s }
[2019-10-29][00:05:09.436446000][DEBUG] [trust_dns_resolver::name_server::name_server] name_server connection failure: tokio spawn error
[2019-10-29][00:05:09.436542000][DEBUG] [trust_dns_resolver::name_server::name_server] reconnecting: NameServerConfig { socket_addr: V4(211.148.192.141:53), protocol: Udp, tls_dns_name: None, tls_config: None }
[2019-10-29][00:05:09.436599000][DEBUG] [trust_dns_resolver::name_server::name_server] reconnecting: NameServerConfig { socket_addr: V4(211.148.192.151:53), protocol: Udp, tls_dns_name: None, tls_config: None }
[2019-10-29][00:05:09.436645000][TRACE] [trust_dns_resolver::name_server::connection_provider] polling response inner
[2019-10-29][00:05:09.436688000][DEBUG] [trust_dns_resolver::name_server::connection_provider] connecting: Udp { socket_addr: V4(211.148.192.141:53), timeout: 5s }
[2019-10-29][00:05:09.436740000][DEBUG] [trust_dns_resolver::name_server::name_server] name_server connection failure: tokio spawn error
[2019-10-29][00:05:09.436771000][TRACE] [trust_dns_resolver::name_server::connection_provider] polling response inner
[2019-10-29][00:05:09.436793000][DEBUG] [trust_dns_resolver::name_server::connection_provider] connecting: Udp { socket_addr: V4(211.148.192.151:53), timeout: 5s }
[2019-10-29][00:05:09.436887000][DEBUG] [trust_dns_resolver::name_server::name_server] name_server connection failure: tokio spawn error
[2019-10-29][00:05:09.436993000][DEBUG] [trust_dns_resolver::name_server::name_server] reconnecting: NameServerConfig { socket_addr: V4(211.148.192.141:53), protocol: Tcp, tls_dns_name: None, tls_config: None }
[2019-10-29][00:05:09.437047000][DEBUG] [trust_dns_resolver::name_server::name_server] reconnecting: NameServerConfig { socket_addr: V4(211.148.192.151:53), protocol: Tcp, tls_dns_name: None, tls_config: None }
[2019-10-29][00:05:09.437115000][TRACE] [trust_dns_resolver::name_server::connection_provider] polling response inner
[2019-10-29][00:05:09.437155000][DEBUG] [trust_dns_resolver::name_server::connection_provider] connecting: Tcp { socket_addr: V4(211.148.192.141:53), timeout: 5s }
[2019-10-29][00:05:09.437267000][DEBUG] [trust_dns_resolver::name_server::name_server] name_server connection failure: tokio spawn error
[2019-10-29][00:05:09.437325000][TRACE] [trust_dns_resolver::name_server::connection_provider] polling response inner
[2019-10-29][00:05:09.437362000][DEBUG] [trust_dns_resolver::name_server::connection_provider] connecting: Tcp { socket_addr: V4(211.148.192.151:53), timeout: 5s }
[2019-10-29][00:05:09.437464000][DEBUG] [trust_dns_resolver::name_server::name_server] name_server connection failure: tokio spawn error
[2019-10-29][00:05:09.437641000][DEBUG] [trust_dns_proto::xfer::dns_handle] querying: www.example.com AAAA
[2019-10-29][00:05:09.437796000][DEBUG] [trust_dns_resolver::name_server::name_server] reconnecting: NameServerConfig { socket_addr: V4(211.148.192.151:53), protocol: Udp, tls_dns_name: None, tls_config: None }
[2019-10-29][00:05:09.437854000][DEBUG] [trust_dns_resolver::name_server::name_server] reconnecting: NameServerConfig { socket_addr: V4(211.148.192.141:53), protocol: Udp, tls_dns_name: None, tls_config: None }
[2019-10-29][00:05:09.437922000][TRACE] [trust_dns_resolver::name_server::connection_provider] polling response inner
[2019-10-29][00:05:09.437952000][DEBUG] [trust_dns_resolver::name_server::connection_provider] connecting: Udp { socket_addr: V4(211.148.192.151:53), timeout: 5s }
[2019-10-29][00:05:09.438054000][DEBUG] [trust_dns_resolver::name_server::name_server] name_server connection failure: tokio spawn error
[2019-10-29][00:05:09.438106000][TRACE] [trust_dns_resolver::name_server::connection_provider] polling response inner
[2019-10-29][00:05:09.438137000][DEBUG] [trust_dns_resolver::name_server::connection_provider] connecting: Udp { socket_addr: V4(211.148.192.141:53), timeout: 5s }
[2019-10-29][00:05:09.438194000][DEBUG] [trust_dns_resolver::name_server::name_server] name_server connection failure: tokio spawn error
[2019-10-29][00:05:09.438305000][DEBUG] [trust_dns_resolver::name_server::name_server] reconnecting: NameServerConfig { socket_addr: V4(211.148.192.151:53), protocol: Tcp, tls_dns_name: None, tls_config: None }
[2019-10-29][00:05:09.438365000][DEBUG] [trust_dns_resolver::name_server::name_server] reconnecting: NameServerConfig { socket_addr: V4(211.148.192.141:53), protocol: Tcp, tls_dns_name: None, tls_config: None }
[2019-10-29][00:05:09.438426000][TRACE] [trust_dns_resolver::name_server::connection_provider] polling response inner
[2019-10-29][00:05:09.438479000][DEBUG] [trust_dns_resolver::name_server::connection_provider] connecting: Tcp { socket_addr: V4(211.148.192.151:53), timeout: 5s }
[2019-10-29][00:05:09.438566000][DEBUG] [trust_dns_resolver::name_server::name_server] name_server connection failure: tokio spawn error
[2019-10-29][00:05:09.438608000][TRACE] [trust_dns_resolver::name_server::connection_provider] polling response inner
[2019-10-29][00:05:09.438631000][DEBUG] [trust_dns_resolver::name_server::connection_provider] connecting: Tcp { socket_addr: V4(211.148.192.141:53), timeout: 5s }
[2019-10-29][00:05:09.438690000][DEBUG] [trust_dns_resolver::name_server::name_server] name_server connection failure: tokio spawn error
[2019-10-29][00:05:09.438868000][DEBUG] [trust_dns_resolver::name_server::name_server] reconnecting: NameServerConfig { socket_addr: V4(211.148.192.141:53), protocol: Udp, tls_dns_name: None, tls_config: None }
[2019-10-29][00:05:09.438930000][DEBUG] [trust_dns_resolver::name_server::name_server] reconnecting: NameServerConfig { socket_addr: V4(211.148.192.151:53), protocol: Udp, tls_dns_name: None, tls_config: None }
[2019-10-29][00:05:09.439010000][TRACE] [trust_dns_resolver::name_server::connection_provider] polling response inner
[2019-10-29][00:05:09.439040000][DEBUG] [trust_dns_resolver::name_server::connection_provider] connecting: Udp { socket_addr: V4(211.148.192.141:53), timeout: 5s }
[2019-10-29][00:05:09.439102000][DEBUG] [trust_dns_resolver::name_server::name_server] name_server connection failure: tokio spawn error
[2019-10-29][00:05:09.439136000][TRACE] [trust_dns_resolver::name_server::connection_provider] polling response inner
[2019-10-29][00:05:09.439160000][DEBUG] [trust_dns_resolver::name_server::connection_provider] connecting: Udp { socket_addr: V4(211.148.192.151:53), timeout: 5s }
[2019-10-29][00:05:09.439207000][DEBUG] [trust_dns_resolver::name_server::name_server] name_server connection failure: tokio spawn error
[2019-10-29][00:05:09.439297000][DEBUG] [trust_dns_resolver::name_server::name_server] reconnecting: NameServerConfig { socket_addr: V4(211.148.192.141:53), protocol: Tcp, tls_dns_name: None, tls_config: None }
[2019-10-29][00:05:09.439350000][DEBUG] [trust_dns_resolver::name_server::name_server] reconnecting: NameServerConfig { socket_addr: V4(211.148.192.151:53), protocol: Tcp, tls_dns_name: None, tls_config: None }
[2019-10-29][00:05:09.439394000][TRACE] [trust_dns_resolver::name_server::connection_provider] polling response inner
[2019-10-29][00:05:09.439418000][DEBUG] [trust_dns_resolver::name_server::connection_provider] connecting: Tcp { socket_addr: V4(211.148.192.141:53), timeout: 5s }
[2019-10-29][00:05:09.439479000][DEBUG] [trust_dns_resolver::name_server::name_server] name_server connection failure: tokio spawn error
[2019-10-29][00:05:09.439512000][TRACE] [trust_dns_resolver::name_server::connection_provider] polling response inner
[2019-10-29][00:05:09.439534000][DEBUG] [trust_dns_resolver::name_server::connection_provider] connecting: Tcp { socket_addr: V4(211.148.192.151:53), timeout: 5s }
[2019-10-29][00:05:09.439585000][DEBUG] [trust_dns_resolver::name_server::name_server] name_server connection failure: tokio spawn error
[2019-10-29][00:05:09.439683000][DEBUG] [trust_dns_resolver::name_server::name_server] reconnecting: NameServerConfig { socket_addr: V4(211.148.192.151:53), protocol: Udp, tls_dns_name: None, tls_config: None }
[2019-10-29][00:05:09.439740000][DEBUG] [trust_dns_resolver::name_server::name_server] reconnecting: NameServerConfig { socket_addr: V4(211.148.192.141:53), protocol: Udp, tls_dns_name: None, tls_config: None }
[2019-10-29][00:05:09.439784000][TRACE] [trust_dns_resolver::name_server::connection_provider] polling response inner
[2019-10-29][00:05:09.439807000][DEBUG] [trust_dns_resolver::name_server::connection_provider] connecting: Udp { socket_addr: V4(211.148.192.151:53), timeout: 5s }
[2019-10-29][00:05:09.439859000][DEBUG] [trust_dns_resolver::name_server::name_server] name_server connection failure: tokio spawn error
[2019-10-29][00:05:09.439889000][TRACE] [trust_dns_resolver::name_server::connection_provider] polling response inner
[2019-10-29][00:05:09.439910000][DEBUG] [trust_dns_resolver::name_server::connection_provider] connecting: Udp { socket_addr: V4(211.148.192.141:53), timeout: 5s }
[2019-10-29][00:05:09.439954000][DEBUG] [trust_dns_resolver::name_server::name_server] name_server connection failure: tokio spawn error
[2019-10-29][00:05:09.440032000][DEBUG] [trust_dns_resolver::name_server::name_server] reconnecting: NameServerConfig { socket_addr: V4(211.148.192.151:53), protocol: Tcp, tls_dns_name: None, tls_config: None }
[2019-10-29][00:05:09.440082000][DEBUG] [trust_dns_resolver::name_server::name_server] reconnecting: NameServerConfig { socket_addr: V4(211.148.192.141:53), protocol: Tcp, tls_dns_name: None, tls_config: None }
[2019-10-29][00:05:09.440128000][TRACE] [trust_dns_resolver::name_server::connection_provider] polling response inner
[2019-10-29][00:05:09.440150000][DEBUG] [trust_dns_resolver::name_server::connection_provider] connecting: Tcp { socket_addr: V4(211.148.192.151:53), timeout: 5s }
[2019-10-29][00:05:09.440206000][DEBUG] [trust_dns_resolver::name_server::name_server] name_server connection failure: tokio spawn error
[2019-10-29][00:05:09.440237000][TRACE] [trust_dns_resolver::name_server::connection_provider] polling response inner
[2019-10-29][00:05:09.440258000][DEBUG] [trust_dns_resolver::name_server::connection_provider] connecting: Tcp { socket_addr: V4(211.148.192.141:53), timeout: 5s }
[2019-10-29][00:05:09.440308000][DEBUG] [trust_dns_resolver::name_server::name_server] name_server connection failure: tokio spawn error
[2019-10-29][00:05:09.440377000][ERROR] [shadowsocks::relay::dns_resolver] Failed to resolve www.example.com:80, err: proto error
```

**To Reproduce**

1. Create a `AsyncResolver` with `read_system_conf`

    ```rust
    let (config, opts) = read_system_conf().expect("Failed to read global dns sysconf");
    let (resolver, bg) = AsyncResolver::new(config, opts);

    tokio::spawn(bg);  // Runs background task.
    ```

2.  Call `lookup_ip` with any addresses

    ```rust
    let addrs = resolver.lookup_ip("www.example.com").await?;
    ```

**Expected behavior**

`lookup_ip`  should return valid IPs instead of errors.

**System:**
 - OS: macOS 10.14.6
 - Architecture: x86_64
 - Version: ?
 - rustc version: 1.39.0-beta.7 (23f8f652b 2019-10-26)

**Version:**
Crate: resolver
Version: master on github

**Comment by bluejekyll** [comment]
Do you have the code for how tokio itself is being instantiated?

**Comment by bluejekyll** [comment]
In some of the async/await changes, I think some lazy's were removed, this could be an issue in some cases.

**Comment by zonyitoo** [comment]
I am using `#[tokio::main]`.

```rust
#[tokio::main]
async fn main() {
    // ...
}
```

**Comment by zonyitoo** [comment]
This is how I instantiated tokio: https://github.com/shadowsocks/shadowsocks-rust/blob/feature-migrate-async-await/src/bin/server.rs#L25 .

In `run_server` function,  `AsyncResolver` is instanciated in `Context::new`: https://github.com/shadowsocks/shadowsocks-rust/blob/feature-migrate-async-await/src/relay/server.rs#L18 .

`Context::new`: https://github.com/shadowsocks/shadowsocks-rust/blob/feature-migrate-async-await/src/context.rs#L19 .

`create_resolver`: https://github.com/shadowsocks/shadowsocks-rust/blob/feature-migrate-async-await/src/relay/dns_resolver.rs#L14

**Comment by bluejekyll** [comment]
Ok, using this comparison: https://github.com/bluejekyll/trust-dns/compare/4858edd3e74434e21bfa8c1a04b5a2d0459967da...master

My guess is that some of the lazy's that were removed in that patch are causing issues.

**Comment by bluejekyll** [comment]
@zonyitoo if you have time, do you think you could throw together a test case that we can reproduce this problem with and we could use that as the basis for finding this issue and making sure it doesn’t happen again?

**Comment by bluejekyll** [comment]
Ok, thanks. I'll pull this into the repo and use as a new test case to make sure we're compatible with the usage of `#[tokio::main]`, my theory is that something is not as lazy as it should be during construction, but not sure why it's different based on the way tokio is instantiated.

I might have time to look at this tonight, but can't guarantee it.

**Comment by zonyitoo** [comment]
I don't think `#[tokio::main]` is the one to be blamed. Here is another test case with `Runtime`:

```rust
use trust_dns_resolver::AsyncResolver;
use trust_dns_resolver::system_conf::read_system_conf;

use tokio;
use tokio::runtime::Runtime;

fn main() {
    let runtime = Runtime::new().unwrap();

    let resolved = runtime.block_on(async {
        let (config, opts) = read_system_conf().expect("Failed to read global dns sysconf");
        let (resolver, bg) = AsyncResolver::new(config, opts);

        tokio::spawn(bg);

        resolver.lookup_ip("www.example.com").await
    }).unwrap();

    println!("{:?}", resolved);
}
```

**Comment by zonyitoo** [comment]
This is exactly the test in [async_resolver/mod.rs](https://github.com/bluejekyll/trust-dns/blob/master/crates/resolver/src/async_resolver/mod.rs#L422).

```rust
use trust_dns_resolver::config::{ResolverConfig, ResolverOpts};
use trust_dns_resolver::AsyncResolver;

use tokio::runtime::Runtime;

fn main() {
    let runtime = Runtime::new().unwrap();

    let (resolver, bg) = AsyncResolver::new(ResolverConfig::default(), ResolverOpts::default());

    runtime.spawn(bg);

    let resolved = runtime.block_on(resolver.lookup_ip("www.example.com")).unwrap();
    println!("{:?}", resolved);
}
```

Not surprised ...

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ResolveError { inner: ProtoError { inner: SpawnError { is_shutdown: true }

tokio spawn error }

proto error }', src/libcore/result.rs:1165:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**Comment by bluejekyll** [comment]
> I don't think #[tokio::main] is the one to be blamed. Here is another test case with Runtime:

I wasn't implying it's at fault, just that it's exposing an issue in the library that wasn't there before.

What's confusing here is that this test passes in CI without issue, and on mac (also locally for me as well): https://travis-ci.org/bluejekyll/trust-dns/jobs/604008906#L842

I wonder if we're masking some other error?

**Comment by bluejekyll** [comment]
Ok, here's why the tests are passing, change your dependency on tokio to `tokio = "0.2.0-alpha"`, and your example passes.

So something about tokio master is different enough to break trust-dns.

**Comment by bluejekyll** [comment]
Ok, see feedback on linked issue. After looking at the cargo tree output, I think it's clear that there are multiple dependency versions being used at once from tokio. Please use `0.2.0-alpha` from tokio, and most likely, it might be best to use the latest 0.18.0-alpha for trust-dns as well.

**Comment by zonyitoo** [comment]
Well, it works after changing deps of `tokio`.

**Comment by zonyitoo** [comment]
Closing now.

**Comment by bluejekyll** [comment]
If you want to use master, you’ll need do something to tell all the trust-dns libraries to also use master, it is possible: https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#overriding-dependencies

**Comment by zonyitoo** [comment]
That's very helpful!!  Thanks!

**Comment by zonyitoo** [comment]
But it seems that trust-dns cannot build with tokio's master

```
   Compiling trust-dns-proto v0.18.0-alpha.1 (https://github.com/bluejekyll/trust-dns#7de3f7b7)
error[E0432]: unresolved import `tokio_net::tcp`
   --> /Users/zonyitoo/.cargo/git/checkouts/trust-dns-97a7602ad159d348/7de3f7b/crates/proto/src/tcp/tcp_client_stream.rs:128:16
    |
128 | use tokio_net::tcp::TcpStream as TokioTcpStream;
    |                ^^^ could not find `tcp` in `tokio_net`

error[E0432]: unresolved import `tokio_net::udp`
   --> /Users/zonyitoo/.cargo/git/checkouts/trust-dns-97a7602ad159d348/7de3f7b/crates/proto/src/udp/udp_stream.rs:316:5
    |
316 | use tokio_net::udp;
    |     ^^^^^^^^^^^^^^ no `udp` in the root

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0432`.
error: could not compile `trust-dns-proto`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by zonyitoo** [comment]
These two errors  could be fixed by replacing `tokio_net` with `tokio::net`.

**Comment by bluejekyll** [comment]
We don’t want to directly depend on Tokio, as that pulls in too many dependencies for the proto library. Dod you overrode the version dependency for all of the Tokio child libraries?

**Comment by zonyitoo** [comment]
I don't think that will work. Some of the child libraries have been merged completely into `tokio`, such as `tokio-process`, `tokio-signal`, `tokio-io`, `tokio-net`, ...

**Comment by cg31** [comment]
sub crate tokio-net was removed in tokio trunk:
https://github.com/tokio-rs/tokio/commit/227533d456fe32e48ffcd3796f1e6c8f9318b230#diff-35f61802211c050cff4d28bd6cd086e0

**Comment by bluejekyll** [comment]
Thanks for this note. I’m going to ping the Tokio dev channel to get some guidance.

**Comment by zonyitoo** [comment]
Remind: tokio v0.2.0 is released.

**Comment by kpcyrd** [comment]
I think I ran into the same issue after upgrading from osx 10.12 to 10.13. I'm on trust-dns 0.17.0 and trust-dns-proto 0.8.0.

Removing the fe80::/10 address from /etc/resolv.conf fixed this. I assume this error might be related to ipv6.

**Comment by bluejekyll** [comment]
Any chance you can upgrade to 0.19?

**Comment by zonyitoo** [comment]
Already upgraded. But found another warnings:

```
[2020-03-17T19:55:54Z WARN  trust_dns_proto::xfer] error notifying wait, possible future leak: Err(ProtoError { kind: Message("requestor canceled"), backtrack: None })
```

But errors in this issue is not showing again.
